name: e_mall
description: "An E-Commerce App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utility packages
  get: ^4.6.5
  url_launcher: ^6.1.12
  get_storage: ^2.0.3
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  carousel_slider: ^4.2.1

#Product Specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/on-boarding-images/
    - assets/images/animations/
    - assets/images/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/brands/
    - assets/images/user/
