// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoixgsDSKj-da4L8rXoznf92FPY5ljkS0',
    appId: '1:272863459759:web:62bec38320ef988801d75a',
    messagingSenderId: '272863459759',
    projectId: 'ecommerceapp-80dad',
    authDomain: 'ecommerceapp-80dad.firebaseapp.com',
    storageBucket: 'ecommerceapp-80dad.appspot.com',
    measurementId: 'G-VVZNJ2J79X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRV4U6Cd0hE3adTTxNGEfsiqMHtcc0uA',
    appId: '1:272863459759:android:85183f132832e35b01d75a',
    messagingSenderId: '272863459759',
    projectId: 'ecommerceapp-80dad',
    storageBucket: 'ecommerceapp-80dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Zt5rRM__nrZmBjDB3iGsDgByfYeFQHg',
    appId: '1:272863459759:ios:efebabe3f46099c501d75a',
    messagingSenderId: '272863459759',
    projectId: 'ecommerceapp-80dad',
    storageBucket: 'ecommerceapp-80dad.appspot.com',
    androidClientId: '272863459759-u7kmlnhd1kp6osbisf048anmsb164phb.apps.googleusercontent.com',
    iosClientId: '272863459759-kn060f6mdmvjlm73kbhv72asncb4i7vi.apps.googleusercontent.com',
    iosBundleId: 'com.emall.eMall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Zt5rRM__nrZmBjDB3iGsDgByfYeFQHg',
    appId: '1:272863459759:ios:efebabe3f46099c501d75a',
    messagingSenderId: '272863459759',
    projectId: 'ecommerceapp-80dad',
    storageBucket: 'ecommerceapp-80dad.appspot.com',
    androidClientId: '272863459759-u7kmlnhd1kp6osbisf048anmsb164phb.apps.googleusercontent.com',
    iosClientId: '272863459759-kn060f6mdmvjlm73kbhv72asncb4i7vi.apps.googleusercontent.com',
    iosBundleId: 'com.emall.eMall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoixgsDSKj-da4L8rXoznf92FPY5ljkS0',
    appId: '1:272863459759:web:5121397b18b52e0801d75a',
    messagingSenderId: '272863459759',
    projectId: 'ecommerceapp-80dad',
    authDomain: 'ecommerceapp-80dad.firebaseapp.com',
    storageBucket: 'ecommerceapp-80dad.appspot.com',
    measurementId: 'G-3GR2GE42B4',
  );

}