// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6oYd5wKTGgWJU2aHaSng2_cPQ3EfXiM',
    appId: '1:669569543081:web:b8c70710e37afecbe1f2b8',
    messagingSenderId: '669569543081',
    projectId: 'emall-5784f',
    authDomain: 'emall-5784f.firebaseapp.com',
    storageBucket: 'emall-5784f.appspot.com',
    measurementId: 'G-JQFNYZ58F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnJ3O_-3z4fVArvawnogYHoxmYtcsH8M',
    appId: '1:669569543081:android:89c2c2a0926a68aee1f2b8',
    messagingSenderId: '669569543081',
    projectId: 'emall-5784f',
    storageBucket: 'emall-5784f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9hRAPGWwt7pOnSa5GZn3gzF_u4e1SLj8',
    appId: '1:669569543081:ios:d40e23945663b6ebe1f2b8',
    messagingSenderId: '669569543081',
    projectId: 'emall-5784f',
    storageBucket: 'emall-5784f.appspot.com',
    iosClientId: '669569543081-9rg0abaophps3kvk83he37p5fp4euia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9hRAPGWwt7pOnSa5GZn3gzF_u4e1SLj8',
    appId: '1:669569543081:ios:d40e23945663b6ebe1f2b8',
    messagingSenderId: '669569543081',
    projectId: 'emall-5784f',
    storageBucket: 'emall-5784f.appspot.com',
    iosClientId: '669569543081-9rg0abaophps3kvk83he37p5fp4euia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6oYd5wKTGgWJU2aHaSng2_cPQ3EfXiM',
    appId: '1:669569543081:web:aa7be29f7a8eed6ce1f2b8',
    messagingSenderId: '669569543081',
    projectId: 'emall-5784f',
    authDomain: 'emall-5784f.firebaseapp.com',
    storageBucket: 'emall-5784f.appspot.com',
    measurementId: 'G-G5GW1C58KN',
  );

}